language: cpp
os : linux
compiler: clang
sudo: required

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE=Release
    - compiler: gcc
      env: BUILD_TYPE=Release
    - compiler: clang
      env: BUILD_TYPE=Release
    - compiler: clang
      env: BUILD_TYPE=Release
      
install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh
  - sudo sh cmake-3.9.2-Linux-x86_64.sh -- --skip-license --prefix=/usr

script:
  - sudo sh autoupdate.sh
  - mkdir build ; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --config $BUILD_TYPE
  - cmake --build . --target install
