language: cpp
sudo : false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      env:
      - COMPILERCXX="g++-5"
      - COMPILERC="gcc-5"
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5             #libstdc++5 required
before_script:
  - if [ -n "$COMPILERC" ]; then export CC=$COMPILERC; fi
  - if [ -n "$COMPILERCXX" ]; then export CXX=$COMPILERCXX; fi 
      
install:

script:
  - sh autoupdate.sh
  - cd orencash/src
  - mkdir build ; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build .
